name: Go release
#
on:
  release:
    types: [published]
#
jobs:
  build:
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    go-version: [ '1.18.x', '1.19.x', '1.20.x', '1.21.x' ]
    steps:
    - uses: actions/checkout@v3
    #
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: true
    #
    - name: Upload nomad-binary #${{ matrix.go-version }}
      uses: actions/upload-artifact@v3
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        name: upload-nomad-binary-${{ matrix.go-version }}
        path: /tmp/bin/nomad-binary.tar
    #
    - name: Release FFmpeg ${{ matrix.go-version }}
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: "# Release ${{github.ref}} \n"
        files: |
          LICENSE
          /tmp/bin/nomad-binary.tar